# Generated by Django 4.0 on 2021-12-26 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dictionary_name', models.CharField(max_length=255, verbose_name='Dictionary name')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Dictionary',
                'verbose_name_plural': 'Dictionaries',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_rus', models.CharField(max_length=255, verbose_name='Word(rus)')),
                ('word_eng', models.CharField(max_length=255, verbose_name='Word(eng)')),
                ('is_trouble', models.BooleanField(default=False, verbose_name='Word with trouble')),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word_trainer.dictionary', verbose_name='Dictionary')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ('word_rus',),
            },
        ),
    ]

